### ISSUE TITLE
'Edit on GitHub' links broken

### ISSUE THREAD

**Issue by keckler** [terrapower/terrapower.github.io#6] opened 2021-12-06 18:05 UTC
It appears that the 'Edit on GitHub' links at the top-right of many of the doc pages are broken. Not all of them are broken, for instance the ones on the [home page](https://terrapower.github.io/armi/index.html), [installation page](https://terrapower.github.io/armi/installation.html), and [tutorials page](https://terrapower.github.io/armi/tutorials/index.html) work. But at least the following ones are broken (and likely many others):
- [gallery](https://terrapower.github.io/armi/gallery/index.html)
- [physics package](https://terrapower.github.io/armi/.apidocs/armi.physics.html)
- [neutronics package](https://terrapower.github.io/armi/.apidocs/armi.physics.neutronics.html)
- [energyGroups module](https://terrapower.github.io/armi/.apidocs/armi.physics.neutronics.energyGroups.html)

![image](https://user-images.githubusercontent.com/21959600/144898523-e7979a7a-77b6-4031-927c-c744cc605a22.png)

**Comment by john-science** [comment] 2021-12-07 05:45
I can confirm this issue is live.

This is a totally automated feature that we didn't write or even turn on.  It just _came_ with one of our Sphinx extensions, and I can't tell which one.

It is probable that the only way to remove these errors will be to remove the "Edit on GitHub" links from _all_ pages, even the ones that are currently working, e.g.  https://stackoverflow.com/questions/36019670/removing-the-edit-on-github-link-when-using-read-the-docs-sphinx-with-readthed

https://docs.readthedocs.io/en/latest/guides/remove-edit-buttons.html#

It might be possible to fix or remove the broken Edit links.  More research would be needed though.

**Comment by keckler** [comment] 2021-12-07 15:45
No problem, its not a pressing issue. Just wanted to make sure the issue was documented.

**Comment by ntouran** [comment] 2021-12-07 16:30
This is a feature of the sphinx-rtd-theme sphinx theme and it seems to be mostly broken on auto-generated pages as opposed to narrative rst files that we have in the armi repo. This is very similar to https://github.com/rwth-i6/returnn/issues/401

**Comment by john-science** [comment] 2021-12-10 17:14
I have a working fix for this.  Incoming.

**Closed as completed** 2021-12-13 23:38 UTC
Labels: documentation

**Comment by john-science** [comment] 2021-12-13 23:39
The first for this is in. The automated system will rebuild the docs and deploy them in 5-30 minutes or so.
